version: '3'
services:
  zk1:
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - 12181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
    volumes:
      - ./volumes/zk1/data:/var/lib/zookeeper/data
      - ./volumes/zk1/log:/var/lib/zookeeper/log
    hostname: zk1
    container_name: cdc-zk1
  zk2:
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - 22181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
    volumes:
      - ./volumes/zk2/data:/var/lib/zookeeper/data
      - ./volumes/zk2/log:/var/lib/zookeeper/log
    hostname: zk2
    container_name: cdc-zk2
  zk3:
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - 32181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
    volumes:
      - ./volumes/zk3/data:/var/lib/zookeeper/data
      - ./volumes/zk3/log:/var/lib/zookeeper/log
    hostname: zk3
    container_name: cdc-zk3
  kf1:
    image: confluentinc/cp-kafka:7.3.2
    depends_on: [zk1,zk2,zk3]
    ports:
      - 19092:19092
    environment:
      # understand config: https://www.confluent.io/blog/kafka-listeners-explained/
      # TODO: build custom image to reduce repeatitive
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kf1:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 1000000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1000000000
      KAFKA_MESSAGE_MAX_BYTES: 1000000000
      KAFKA_MAX_MESSAGE_BYTES: 1000000000
    volumes:
      - ./volumes/kf1:/var/lib/kafka/data
    hostname: kf1
    container_name: cdc-kf1
    restart: always
  kf2:
    image: confluentinc/cp-kafka:7.3.2
    depends_on: [zk1,zk2,zk3]
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kf2:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 1000000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1000000000
      KAFKA_MESSAGE_MAX_BYTES: 1000000000
      KAFKA_MAX_MESSAGE_BYTES: 1000000000
    volumes:
      - ./volumes/kf2:/var/lib/kafka/data
    hostname: kf2
    container_name: cdc-kf2
    restart: always
  kf3:
    image: confluentinc/cp-kafka:7.3.2
    depends_on: [zk1,zk2,zk3]
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:39092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kf3:9092,OUTSIDE://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 1000000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1000000000
      KAFKA_MESSAGE_MAX_BYTES: 1000000000
      KAFKA_MAX_MESSAGE_BYTES: 1000000000
    volumes:
      - ./volumes/kf3:/var/lib/kafka/data
    hostname: kf3
    container_name: cdc-kf3
    restart: always
  kc1:
    image: confluentinc/cp-kafka-connect:7.3.2
    depends_on: [kf1,kf2,kf3]
    ports:
      - 8083:8083
    environment:
      CONNECT_GROUP_ID: konnect
      CONNECT_BOOTSTRAP_SERVERS: kf1:9092,kf2:9092,kf3:9092
      CONNECT_CONFIG_STORAGE_TOPIC: _konnect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _konnect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _konnect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kc1
      CONNECT_REST_PORT: 8083
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_PRODUCER_MAX_REQUEST_SIZE: 1000000000
    volumes:
      - ./volumes/kc1/data:/var/lib/kafka/data
    command:
      - bash
      - -c
      - |
        echo "Installing connector plugins"
        confluent-hub install --no-prompt confluentinc/kafka-connect-aws-lambda:2.0.6
        confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.0.1
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        sleep infinity
    hostname: kc1
    container_name: cdc-kc1
  kc2:
    image: confluentinc/cp-kafka-connect:7.3.2
    depends_on: [kf1,kf2,kf3]
    environment:
      CONNECT_GROUP_ID: konnect
      CONNECT_BOOTSTRAP_SERVERS: kf1:9092,kf2:9092,kf3:9092
      CONNECT_CONFIG_STORAGE_TOPIC: _konnect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _konnect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _konnect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kc2
      CONNECT_REST_PORT: 8083
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_PRODUCER_MAX_REQUEST_SIZE: 1000000000
    volumes:
      - ./volumes/kc2/data:/var/lib/kafka/data
    command:
      - bash
      - -c
      - |
        echo "Installing connector plugins"
        confluent-hub install --no-prompt confluentinc/kafka-connect-aws-lambda:2.0.6
        confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.0.1
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        sleep infinity
    hostname: kc2
    container_name: cdc-kc2
  kc3:
    image: confluentinc/cp-kafka-connect:7.3.2
    depends_on: [kf1,kf2,kf3]
    environment:
      CONNECT_GROUP_ID: konnect
      CONNECT_BOOTSTRAP_SERVERS: kf1:9092,kf2:9092,kf3:9092
      CONNECT_CONFIG_STORAGE_TOPIC: _konnect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _konnect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _konnect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kc3
      CONNECT_REST_PORT: 8083
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_PRODUCER_MAX_REQUEST_SIZE: 1000000000
    volumes:
      - ./volumes/kc2/data:/var/lib/kafka/data
    command:
      - bash
      - -c
      - |
        echo "Installing connector plugins"
        confluent-hub install --no-prompt confluentinc/kafka-connect-aws-lambda:2.0.6
        confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.0.1
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        sleep infinity
    hostname: kc3
    container_name: cdc-kc3
  kowl:
    image: quay.io/cloudhut/kowl:v1.3.1
    restart: always
    ports:
      - 8079:8080
    depends_on: [kf1,kf2,kf3]
    environment:
      - KAFKA_BROKERS=kf1:9092,kf2:9092,kf3:9092
    container_name: cdc-kowl
